name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/649260330076/locations/global/workloadIdentityPools/github-pool/providers/github'
          service_account: 'github-cicd@sonorous-earth-467917-n1.iam.gserviceaccount.com'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud --quiet auth configure-docker europe-central2-a-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t europe-central2-a-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/python-gke-demo/python-app:${{ github.sha }} .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/python-gke-demo/python-app:${{ github.sha }}
          
      - name: Set up kubectl
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: 'python-gke-demo'           # (Use your real GKE cluster name)
          location: 'europe-central2-a'               # (Or your actual cluster region)

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/python-app python-app=europe-central2-a-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/python-gke-demo/python-app:${{ github.sha }} --namespace=default
          kubectl rollout status deployment/python-app --namespace=default
